### Créer une nouvelle souscription
POST http://localhost:8082/api/subscriptions
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NjgxODU1MiwiZXhwIjoxNzQ2ODIyMTUyfQ.gu5a0tGu2yV7WpCuyBb1I2YTKAj6u43xphDl5OipXqUb5oQl5Od5BIZVdmS1LVy8RN_Nox80WiF-NAn14w5UJfW-SteP3jIpOT0TiLD_jxvnRdLActhC7Wq3p5RohImL8F3ms1ujhYMiTxGjSR-Z2LOfOMDTR3QlT9yhS8UUtZzEzgM4BZCTPJFgChWuCGFUCz2oqktNIHzDwWJHPNlekS60_WrebdPk6LRN5jUMUlSuSRa2DAyDJtSQmJUdZqaIoy84vUbf3KPrnUGKFje-6UJZk1jEOLV_tzNoxYX95YbABISWj1BxSpQDv3ubCo1K5eWLHLtD64HkHRlab27ZUA
Content-Type: application/json

{
  "agencyName": "AgenceAlpha",
  "planType": "Premium"
}

### Lister toutes les souscriptions
GET http://localhost:8082/api/subscriptions
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NjgxODU1MiwiZXhwIjoxNzQ2ODIyMTUyfQ.gu5a0tGu2yV7WpCuyBb1I2YTKAj6u43xphDl5OipXqUb5oQl5Od5BIZVdmS1LVy8RN_Nox80WiF-NAn14w5UJfW-SteP3jIpOT0TiLD_jxvnRdLActhC7Wq3p5RohImL8F3ms1ujhYMiTxGjSR-Z2LOfOMDTR3QlT9yhS8UUtZzEzgM4BZCTPJFgChWuCGFUCz2oqktNIHzDwWJHPNlekS60_WrebdPk6LRN5jUMUlSuSRa2DAyDJtSQmJUdZqaIoy84vUbf3KPrnUGKFje-6UJZk1jEOLV_tzNoxYX95YbABISWj1BxSpQDv3ubCo1K5eWLHLtD64HkHRlab27ZUA

### Vérifier si une agence a une souscription valide
GET http://localhost:8082/api/subscriptions/AgenceAlpha/valid
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0Njc1ODQ0MCwiZXhwIjoxNzQ2NzYyMDQwfQ.UjiENMp2SAKpw2f-7_40_aSnO3IGBEHqkvvx2AM0RjE

### Appeler Billing sécurisé
GET http://localhost:8082/api/subscriptions/AgenceAlpha/valid
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTc0NTgzNzk5NSwiZXhwIjoxNzQ1ODQxNTk1fQ.v_PyMgITbVLJ8YykIaBVMM8vOM3IWXYjGdPSGrypZwQ